# Generated by Django 6.0.3 on 2026-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=50, unique=True)),
                ('page_access_token', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiry time. Null means the token does not expire.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facebook Token',
                'verbose_name_plural': 'Facebook Tokens',
            },
        ),
    ]
