# Generated by Django 6.0.3 on 2026-04-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_news', '0002_facebooktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='facebook_post_id',
            field=models.CharField(blank=True, default='', editable=False, help_text='ID of the corresponding Facebook post, set automatically on first publish.', max_length=200),
        ),
    ]
