# Generated by Django 6.0.3 on 2026-04-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_news', '0002_facebooktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='facebook_post_id',
            field=models.CharField(blank=True, default='', editable=False, help_text='ID of the Facebook post created when this article was first published.', max_length=100),
        ),
    ]
