# Generated by Django 5.0.3 on 2025-04-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollpage',
            name='year',
            field=models.IntegerField(default=2025, help_text='Ročník, do kterého se tým přihlašuje.', verbose_name='Ročník'),
        ),
    ]
