# Generated by Django 5.0.3 on 2025-02-08 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_rename_newsindexpage_newsindexpagecontent"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewsIndexPageContent",
            new_name="NewsIndexPage",
        ),
    ]
