# Generated by Django 5.0.3 on 2025-03-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newspage_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'Aktualita', 'verbose_name_plural': 'Aktuality'},
        ),
    ]
