# Generated by Django 5.0.3 on 2025-03-06 14:18

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMSLPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'O MSL',
                'verbose_name_plural': 'O MSL',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HistoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historie',
                'verbose_name_plural': 'sHistorie',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PointsAndFinancesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Body a fin. ohodnocení',
                'verbose_name_plural': 'Body a fin. ohodnocení',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RoundsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ligová kola',
                'verbose_name_plural': 'Ligová kola',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SeasonParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Sezóna (rok)')),
                ('ranking', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Umístění musí být alespoň 1'), django.core.validators.MaxValueValidator(50, 'Umístění nemůže být větší než 50')], verbose_name='Umístění')),
                ('points', models.IntegerField(verbose_name='Bodové ohodnocení')),
                ('finance', models.IntegerField(verbose_name='Finanční ohodnocení')),
            ],
            options={
                'verbose_name': 'Parametry sezóny',
                'verbose_name_plural': 'Parametry sezón',
            },
        ),
        migrations.CreateModel(
            name='SeasonRounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Sezóna (rok)')),
                ('round', models.CharField(max_length=50, verbose_name='Kolo')),
                ('datetime', models.DateTimeField(verbose_name='Datum konání')),
                ('date_registration', models.DateField(verbose_name='Datum začátku registrace')),
                ('categories', models.CharField(default='Muži, Ženy', max_length=20, verbose_name='Soutěžní kategorie')),
                ('results_ready', models.BooleanField(default=False, verbose_name='Výsledky uveřejněny')),
            ],
            options={
                'verbose_name': 'Ligová kola',
                'verbose_name_plural': 'Ligová kola',
            },
        ),
        migrations.CreateModel(
            name='SeasonTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Sezóna (rok)')),
            ],
            options={
                'verbose_name': 'Tým v sezóně',
                'verbose_name_plural': 'Týmy v sezónách',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Název týmu')),
                ('district', models.CharField(default='XX', max_length=2, verbose_name='Okres')),
                ('category', models.CharField(choices=[('M', 'Muži'), ('Ž', 'Ženy'), ('35+', '35+')], default='M', max_length=50, verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Tým',
                'verbose_name_plural': 'Týmy',
            },
        ),
        migrations.AddConstraint(
            model_name='seasonparameters',
            constraint=models.UniqueConstraint(fields=('season', 'ranking'), name='unique_season_parameters'),
        ),
        migrations.AddConstraint(
            model_name='seasonrounds',
            constraint=models.UniqueConstraint(fields=('season', 'round'), name='unique_season_rounds'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'district', 'category'), name='unique_team'),
        ),
        migrations.AddField(
            model_name='seasonteams',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_teams', to='about_msl.team', verbose_name='Tým'),
        ),
        migrations.AddConstraint(
            model_name='seasonteams',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='unique_season_teams'),
        ),
    ]
