# Generated by Django 5.0.3 on 2025-03-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('founded', models.IntegerField()),
                ('coach', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
