# Generated by Django 5.0.3 on 2025-03-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_msl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historypage',
            options={'verbose_name': 'Historie', 'verbose_name_plural': 'Historie'},
        ),
    ]
