# Generated by Django 5.0.3 on 2025-03-02 09:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_msl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Sezóna (rok)')),
                ('ranking', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Umístění musí být alespoň 1'), django.core.validators.MaxValueValidator(50, 'Umístění nemůže být větší než 50')], verbose_name='Umístění')),
                ('points', models.IntegerField(verbose_name='Bodové ohodnocení')),
                ('finance', models.IntegerField(verbose_name='Finanční ohodnocení')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonRounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Sezóna (rok)')),
                ('round', models.CharField(max_length=50, verbose_name='Kolo')),
                ('datetime', models.DateTimeField(verbose_name='Datum konání')),
                ('date_registration', models.DateField(verbose_name='Datum začátku konání')),
                ('points', models.IntegerField(verbose_name='Bodové ohodnocení')),
                ('finance', models.IntegerField(verbose_name='Finanční ohodnocení')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Sezóna (rok)')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='team',
            name='founded',
        ),
        migrations.AddField(
            model_name='team',
            name='district',
            field=models.CharField(default='XX', max_length=2, verbose_name='Okres'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Název týmu'),
        ),
        migrations.AddConstraint(
            model_name='seasonparameters',
            constraint=models.UniqueConstraint(fields=('season', 'ranking'), name='unique_season_parameters'),
        ),
        migrations.AddConstraint(
            model_name='seasonrounds',
            constraint=models.UniqueConstraint(fields=('season', 'round'), name='unique_season_rounds'),
        ),
        migrations.AddField(
            model_name='seasonteams',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_teams', to='about_msl.team'),
        ),
        migrations.AddConstraint(
            model_name='seasonteams',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='unique_season_teams'),
        ),
    ]
