# Generated by Django 5.0.3 on 2025-03-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_msl', '0002_seasonparameters_seasonrounds_seasonteams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonteams',
            name='season',
            field=models.IntegerField(choices=[(2000, 'Season 2000'), (2001, 'Season 2001'), (2002, 'Season 2002'), (2003, 'Season 2003'), (2004, 'Season 2004'), (2005, 'Season 2005'), (2006, 'Season 2006'), (2007, 'Season 2007'), (2008, 'Season 2008'), (2009, 'Season 2009'), (2010, 'Season 2010'), (2011, 'Season 2011'), (2012, 'Season 2012'), (2013, 'Season 2013'), (2014, 'Season 2014'), (2015, 'Season 2015'), (2016, 'Season 2016'), (2017, 'Season 2017'), (2018, 'Season 2018'), (2019, 'Season 2019'), (2020, 'Season 2020'), (2021, 'Season 2021'), (2022, 'Season 2022'), (2023, 'Season 2023'), (2024, 'Season 2024'), (2025, 'Season 2025'), (2026, 'Season 2026'), (2027, 'Season 2027'), (2028, 'Season 2028'), (2029, 'Season 2029'), (2030, 'Season 2030'), (2031, 'Season 2031'), (2032, 'Season 2032'), (2033, 'Season 2033'), (2034, 'Season 2034'), (2035, 'Season 2035'), (2036, 'Season 2036'), (2037, 'Season 2037'), (2038, 'Season 2038'), (2039, 'Season 2039'), (2040, 'Season 2040'), (2041, 'Season 2041'), (2042, 'Season 2042'), (2043, 'Season 2043'), (2044, 'Season 2044'), (2045, 'Season 2045'), (2046, 'Season 2046'), (2047, 'Season 2047'), (2048, 'Season 2048'), (2049, 'Season 2049'), (2050, 'Season 2050')], verbose_name='Sezóna (rok)'),
        ),
    ]
