# Generated by Django 5.0.3 on 2025-03-02 11:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_msl', '0003_alter_seasonteams_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonparameters',
            options={'verbose_name': 'Tým', 'verbose_name_plural': 'Týmy'},
        ),
        migrations.AlterModelOptions(
            name='seasonteams',
            options={'verbose_name': 'Tým v sezóně', 'verbose_name_plural': 'Týmy v sezónách'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Tým', 'verbose_name_plural': 'Týmy'},
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('M', 'Muži'), ('Ž', 'Ženy'), ('35+', '35+')], default='M', max_length=50, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='seasonteams',
            name='season',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Sezóna (rok)'),
        ),
        migrations.AlterField(
            model_name='seasonteams',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_teams', to='about_msl.team', verbose_name='Tým'),
        ),
    ]
