# Generated by Django 5.0.3 on 2025-03-02 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_msl', '0004_alter_seasonparameters_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonparameters',
            options={'verbose_name': 'Parametry sezóny', 'verbose_name_plural': 'Parametry sezón'},
        ),
        migrations.AlterModelOptions(
            name='seasonrounds',
            options={'verbose_name': 'Ligová kola', 'verbose_name_plural': 'Ligová kola'},
        ),
        migrations.RemoveField(
            model_name='seasonrounds',
            name='finance',
        ),
        migrations.RemoveField(
            model_name='seasonrounds',
            name='points',
        ),
        migrations.AddField(
            model_name='seasonrounds',
            name='caregories',
            field=models.CharField(default='Muži, Ženy', max_length=20, verbose_name='Soutěžní kategorie'),
        ),
        migrations.AddField(
            model_name='seasonrounds',
            name='results_ready',
            field=models.BooleanField(default=False, verbose_name='Výsledky uveřejněny'),
        ),
        migrations.AlterField(
            model_name='seasonparameters',
            name='season',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Sezóna (rok)'),
        ),
    ]
