# Generated by Django 5.0.3 on 2025-03-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_msl', '0005_alter_seasonparameters_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonrounds',
            old_name='caregories',
            new_name='categories',
        ),
    ]
