# Generated by Django 5.1.6 on 2025-03-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_msl', '0006_rename_caregories_seasonrounds_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonrounds',
            name='date_registration',
            field=models.DateField(verbose_name='Datum začátku registrace'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'district', 'category'), name='unique_team'),
        ),
    ]
