# Generated by Django 5.0.3 on 2025-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='district',
            field=models.CharField(default='*', max_length=2, verbose_name='Okres'),
        ),
    ]
