# Generated by Django 5.0.3 on 2025-04-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Schváleno'),
        ),
    ]
