# Generated by Django 5.0.3 on 2025-05-03 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_about', '0002_team_confirmed'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Přihlášky',
                'verbose_name_plural': 'Přihlášky',
            },
            bases=('wagtailcore.page',),
        ),
    ]
