# Generated by Django 5.0.3 on 2025-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_about', '0002_alter_team_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonteams',
            name='date_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Datum registrace'),
        ),
        migrations.AddField(
            model_name='seasonteams',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Startovné zaplaceno'),
        ),
        migrations.AddField(
            model_name='seasonteams',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Registrován'),
        ),
    ]
