# Generated by Django 5.0.3 on 2025-05-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msl_about', '0003_enrollmentspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollpage',
            old_name='email',
            new_name='admin_email',
        ),
    ]
