# Generated by Django 5.0.3 on 2025-04-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_about', '0003_seasonteams_date_registration_seasonteams_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonteams',
            name='team_representative',
            field=models.CharField(max_length=100, null=True, verbose_name='Zástupce týmu'),
        ),
        migrations.AddField(
            model_name='seasonteams',
            name='team_representative_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
