# Generated by Django 5.2.2 on 2025-06-06 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_about', '0004_rename_email_enrollpage_admin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonParametersPenalizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Sezóna (rok)')),
                ('category', models.CharField(choices=[('M', 'Muži'), ('Ž', 'Ženy'), ('35+', '35+')], default='M', max_length=50, verbose_name='Kategorie')),
                ('competitors_borrowed', models.IntegerField(verbose_name='Půjčení závodníci')),
                ('penalization_points', models.IntegerField(verbose_name='Penalizace bodů')),
            ],
            options={
                'verbose_name': 'Penalizace v sezóně',
                'verbose_name_plural': 'Penalizace v sezónách',
                'constraints': [models.UniqueConstraint(fields=('season_year', 'category', 'competitors_borrowed'), name='unique_season_penalizations')],
            },
        ),
    ]
