# Generated by Django 5.2.2 on 2025-07-14 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_about', '0006_seasonteams_results_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonrounds',
            name='round_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Číslo kola'),
        ),
    ]
