# Generated by Django 6.0.2 on 2026-05-15 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_about', '0007_seasonrounds_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonrounds',
            name='pozvanka_pdf',
            field=models.FileField(blank=True, null=True, upload_to='round_pdfs/', verbose_name='Pozvánka (PDF)'),
        ),
        migrations.AddField(
            model_name='seasonrounds',
            name='startovka_text',
            field=models.TextField(blank=True, default='', verbose_name='Startovka (seznam týmů)'),
        ),
        migrations.AddField(
            model_name='seasonrounds',
            name='uploads_force_open',
            field=models.BooleanField(default=False, verbose_name='Nahrávání dokumentů – manuální otevření'),
        ),
        migrations.CreateModel(
            name='RoundDocumentEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('pozvanka', 'Pozvánka'), ('startovka', 'Startovka')], max_length=20, verbose_name='Typ dokumentu')),
                ('edited_by', models.CharField(default='', max_length=254, verbose_name='Upravil')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Čas úpravy')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='Detail')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_edits', to='msl_about.seasonrounds', verbose_name='Kolo')),
            ],
            options={
                'verbose_name': 'Historie úprav dokumentů',
                'verbose_name_plural': 'Historie úprav dokumentů',
                'ordering': ['-edited_at'],
            },
        ),
    ]
