# Generated by Django 6.0.2 on 2026-05-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_about', '0008_seasonrounds_pozvanka_pdf_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE msl_about_seasonrounds SET pozvanka_pdf = NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='seasonrounds',
            name='pozvanka_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Pozvánka (PDF)'),
        ),
    ]
