# Generated by Django 6.0.2 on 2026-06-14 11:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msl_about', '0010_results_excel_field'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Tipovačka',
                'verbose_name_plural': 'Tipovačka',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('M', 'Muži'), ('Ž', 'Ženy'), ('35+', '35+')], max_length=10, verbose_name='Kategorie')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Pozice')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Odesláno')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='msl_about.seasonrounds', verbose_name='Kolo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipped_for', to='msl_about.team', verbose_name='Tým')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL, verbose_name='Tipující')),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tipy',
                'ordering': ['round', 'user_id', 'category', 'position'],
                'constraints': [models.UniqueConstraint(fields=('user', 'round', 'category', 'position'), name='unique_tip_per_slot'), models.UniqueConstraint(fields=('user', 'round', 'category', 'team'), name='unique_team_per_user_round_category'), models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 5)), name='tip_position_between_1_and_5')],
            },
        ),
    ]
