# Generated by Django 6.0.2 on 2026-06-14 19:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msl_tips', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsLeaderboardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Průběžné pořadí',
                'verbose_name_plural': 'Průběžné pořadí',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TipsRoundsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Zadej tipy',
                'verbose_name_plural': 'Zadej tipy',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='tipsindexpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
